---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: observability
spec:
  encryptedData:
    admin-password: AgAiDtkx7i1U7ogi5DfTkg/1nTJtCZluZB7GO3Z1rFqp98IFqH3R9xqTHBKNn3gtrwDrDrODn0S5H4mOpwgwVmjhWfaGB8wk8UupN4zlUjAJbkrbBIBqdP3y7pvRcQgJVemsiJFU/1299rtJq6W5orjsAtdJpEAqYuS1Nd7SRb8KZA1+ixJyqkt92BlUBHIPR/0ZAVxxxXssTO1A9beZHOYxz0c9hOnElNTb4is+MkhLlpChMFBvo17lebJQxACp6MnL6w0GInMk4EZNpq7iwf5hZI8uYVN4TJj0xIBzJk/ZWUTYXouNQI91n7vVaQbjJwaoYwDpZLd5PFoCN/DA9TNpm3PVm2XXRmWUOHI77V8w0iGlLWeH/DNQZ2P22UjPaF+aiDdSyvEDscKZgeWQgaKe6NNNRYVhEgiW4kS6DaQprbqFdI67i1pl3OVh6HRcRzfcZjxi+u++JEwYK/cniytB37xczuM/JcQr01p86f6APRqJeZi4ncaC+XBDins7wYb9YZne4EjWDtA3y2sgIo/0yy367Zoe2HBgrXEXNssppuoTILL8+zBPz+tuvLsQF2u6Ph5LTC7kSoIynfd9TlMWmvKoTgka/V85ZsLUNA7vhWkvwjJOyWZVoY6s6LuQOT1E6rigdjaJtHcUjxX2nBTrtqhiZrt0KZTleu6KHddz6Jm5yXTCgMQy1fVfNAa3D39WI2bOilAZwj8ns4Gpww==
    admin-user: AgBTnBaC1EQCHjRRJ+/DTJvvQEwM1nux/tf/1ZmHH/oTjCQX/JX/fZp0JnScGQfSiYjTnT5MbP0p8s6dItNR0CzDHD0Ml5Of++Vmum3cfcU+TsIAcnW4wY6nGIqRm/tI/lkCFag/+lWgtiKAs5rYJGBAE4fB5NSuQTGE8BM50SGVXhZmYp+wEsSe4R57FY+V2jZB+CBtDqoB2g7QiUT88WfJ0IxpY3UiUCF/jZbjNjBSkLFPJxQOyPIE1geS4QPN+GlJU7SGsaAlQYSCqB52c4r4Zlt358QgS+pvJpO6MdJFlQjoN2oLRG3B5ju+S5/N5ILhDQbdqWESvt9FUxG4rTwBG63cUn6dhkqMGs4KN/n06yyB598UNoy6XuvRv0BvgXTl4VrZZgbRHBSGXCS+dQ4wmlcY01TsLGGdSrDt4ZFZOpD797oga6gIowETPw231jZfn/6LLsqfuAq0uiKl4iyAQjHAdAGF9v8A9Wutinnjfciw/na/ZDQLnNG+tmVE6aoLwYJuBjwyv4ml29SihoPEdUXpl6zT7VB7CeLP8mCXTgTGJwoATa8blM+QCfP+WAGMGsQcN0ZbFgo7X31HzYCpSf+EJmAC5C9ajfcNf5+BuT9zgl9dW5Mp2KUu/+Td4ZTidrJstHSUtcG6nIKeQ0XSTlvmCuQ1AfHNeY1n1gwpB3JBPyFYvWzj1DarwUfegnh5bGBKQw==
  template:
    metadata:
      name: grafana-admin
      namespace: observability
    type: Opaque
