apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Isolates the prod database into its own logical environment
namespace: media-prod

resources:
  - ../../../../base/platform/postgres
  - namespace.yaml
