apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - traefik-gateway.yaml
  - routes/traefik-dashboard-route.yaml

helmCharts:
  - name: traefik
    repo: https://helm.traefik.io/traefik
    version: 41.0.2
    releaseName: traefik
    namespace: traefik
    valuesFile: values.yaml
