apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Isolates the dev database into its own logical environment
namespace: media-dev

resources:
  - ../../../../base/platform/postgres
  - namespace.yaml
