mode: daemonset
presets:
  logsCollection:
    enabled: true
    storeCheckpoints: false
  kubernetesAttributes:
    enabled: true
    extractAllPodLabels: true
    extractAllPodAnnotations: true

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 300m
    memory: 256Mi

config:
  processors:
    memory_limiter:
      check_interval: 1s
      limit_mib: 400
      spike_limit_mib: 100
  exporters:
    otlp_http:
      # Point to the native OTLP endpoint on Loki service (Loki exporter is deprecated)
      logs_endpoint: "http://loki.observability.svc.cluster.local:3100/otlp/v1/logs"
      tls:
        insecure: true # Usually required for internal cluster HTTP communication
  service:
    pipelines:
      logs:
        receivers: [filelog]
        processors: [memory_limiter, k8sattributes, batch]
        exporters: [debug, otlp_http]
      metrics: null
      traces: null
image:
  repository: otel/opentelemetry-collector-contrib
