server:
  resources:
  limits:
    cpu: 500m
    memory: 768Mi
  requests:
    cpu: 50m
    memory: 128Mi

  retentionPeriod: 7d
  persistentVolume:
    enabled: true
    size: 15Gi
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role.kubernetes.io/observability
                operator: In
                values: ["true"]
