apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config-hostpath
  namespace: media

spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: jellyfin-hostpath

  resources:
    requests:
      # PVC is 5Gi but the actual bound PV is 10Gi cus I'm stupid
      storage: 5Gi
