apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config-hostpath
  namespace: media

spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: jellyfin-hostpath

  resources:
    requests:
      storage: 10Gi
