apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-config-pv
spec:
  capacity:
    storage: 10Gi

  accessModes:
    - ReadWriteOnce

  persistentVolumeReclaimPolicy: Retain

  storageClassName: jellyfin-hostpath

  hostPath:
    path: /opt/jellyfin/config
    type: DirectoryOrCreate

  claimRef:
    namespace: media
    name: jellyfin-config-hostpath
