apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: media

resources:
  - route.yaml
  - config-pv.yaml
  - config-pvc.yaml

helmCharts:
  - name: jellyfin
    repo: https://jellyfin.github.io/jellyfin-helm
    version: 2.7.0
    releaseName: jellyfin
    namespace: media
    valuesInline:
      nodeSelector:
        kubernetes.io/hostname: home-server

      ingress:
        main:
          enabled: false

      persistence:
        config:
          enabled: true
          existingClaim: jellyfin-config-hostpath
        media:
          enabled: true
          type: hostPath
          hostPath: /opt/jellyfin/media # The directory you rsynced your music to
          MountPath: /media
