---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgAYBFFZ7kFkPZc/+8qt603/l6VGwuZzH2NY4icf1q/N8xlg1cfiY+gcW+m0RwUjmR0GTCJPPtMfMu43WharHEHZZRP9jfAM2YcXZMPE/ta5MaOpznIIomE4l42qakjF8IQl8VsSblNkQelpDLDKUSEh9dAXvZ4KGV4MAciAgUpnr2xZkhQp5o6K8O6g5L8Nipql96WrGN96wlt8hKhbd0VbFVy41/dtyR8cQCR0kSvg3Cu/kKES4tM/3TAsYpsEZA8FR0oHxX+QDX48SYQghUGDZQRAki7fgtP6bonslGxy7GBQ+3H4pxCwaOsf6dyF76GcJPvbVb/Zhwf1fBjAoQj2zuR2PNUY6jdl97V7edC5HeOW5goffsSb/tHWsVmI5smVUpuau3xUxhfFWW/gZbPNCCF20jEQKX6kNCF7Fduy83ZGINBJ3AfT6DhqTNrQ6o5YvQp2ja7mN7rCx8fn64UQBMa3nHSTYgEQizY7YNAgE+QP9/+w8Byo5SEEG0o2X0hPzH08Y8UXBFC2vnQAv4eoD/UKIWvrkebWzd1a+dR8lncUKzNUkT6oRHKVsv01vA4OeUZgXW32ezCTfKqCB0uVKbgxArpHloXyJSMj7FyBwRVRy/vKBK7u3LRwEM1sNV2Lkdg/C+tsnVIONdFTeF345FXcRi/oppfEXsWvEclvUVfRYXucrndv9CN6yON2iy8xmZWv6qKdHkOhUZFxk7QDFw==
    client_secret: AgCUszTNqD7HHg5SP+7xTBdbn/JEOfr14//+NmsuvW5DQlgCSRxh5hhR6oUNU2wCjfG5B3yOoxb5AZ+DZFjB0MUHylyI66qC1OQYkqkCmMg3fLvramTW8YierhS6MbOT/aRdXBIu2AoMrEmiGkoq4iLpXYnGNkI+IK+sS7NxXy81p7gDjDY0RlpiCZTKuplRPVErOPDqWF6byqCMT3uSriPBJ5BmM2SAn+6q+Am+dTSsMKGr70TlR9q+4232WT5olNgR1YWAYGQc+Jr2xHs+8aCFpAlyB8FmUxhVlMl/5cSwNXxVPsJPGo4hRP8xOy5gDJhATzMZjK+hWD/GVROGYOsNpzMWvUnmrOrMuelr2TY+kVIZ0QVcvW0UrcauPkQXzS4pZQz9lu763PsFr9XzGZPtQAQ20C7DogvR2eaVCcJLHVa3S2JH1vtJ55iea+h6VV1nm26fQbmfmVHc+FRSmxFHygHTXJvlUbDbuC6OYc0HBBzwMWHY/VJ8pcCQ4XD1d2gvQt3wfxE1C5bNea4NX6aGPQGRI8loIg0xhEfVrTXaMn0CzaIqKXjlAozg/96Uk4p6HzKHKXRYPv/ylLkoZahFdc4qZrwohkca7j4I/CaKmT10xlrMX2KMWfGyqb+0sRCBRFXJEkNwyVQF0HsmdNBYT+5wTq2dFYRyM6d6t62bYaWWlqD1wcil4y1cXPNBPAN6WIFgoZVXZi4LhAMjiPgz8+uC71s/Xue/gOOlWI3qdxiyHYfwrobcqRFJhPx6j8fU1fm1RrbuIbQ9i3j7/rA=
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale
    type: Opaque
