apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - sealed-secret.yaml

helmCharts:
  - name: postgresql
    repo: https://charts.bitnami.com/bitnami
    version: 18.7.12
    releaseName: postgres
    valuesFile: values.yaml
