---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: media-tracker-postgres
spec:
  encryptedData:
    password: AgB6DO7dPWJjoZ6qb2CcSCKdvJ6mVsbYmH7q84fAs9jVaVdTwlEEBlAikLAlI3TM7SA0S5ONAFNzc5JQn8uGw1CBfxfn+fF24R3kl7eH8iwl/AeGMDdAq+1C2tPUpAgCCxFOl8R/9QA9Arxq3m5vrbgckl0co4KghhpnuGA3RAVrGktIEvoGSr1O1tOZ77FGP0l516LsZSDjfr/MFOg7l6c9pittB9/FaqOLuVL3Zlo7gTikxUNsu493ppACOnaJjPBYbVt8+WqSN9rpvfGU/FbFN7Yx2FYSZIfxlrBKV9TxE/tM4Duzwsu1vyB93z4+iYEU7XSfJoo/++aqIgjVxeoPDqN+XRsYZGNDf8pobuoXLaoj2j3MgRggT6PbSIN9pAOxfF0tcMqxyCskDCA4n0ctbrtTPYlWt9Es2jOE2KM8269fh9zxznNNXKxLD4eTAz6HUL9AKzcRT3+vOo2aNmFowp09fMSA9dcDrkWNJICHVx+157RMOBOYjDLHlnqBTkd2EN7osn2ukuTujA6UAXq68EjAQf4j2+VjgTinGvCZX2i1vLRjV5fcT2lRVDAc6s+JaVZ05bw2nCWjDhNcw+lG5iDwYA42Q6mmGj4VLjkfsAEIdhueLh/Bjs2DZys9tMWbffsxIn08QtU28YtMTIwSTgdsv7OaKS43VVYEht7zz7lfxpa54ZqPcZhi8+FCtLJvDt5gfMdmXXqJ
    postgres-password: AgBiqbqLjYWLmwXKy37FRklrEWrO/fKHzqLJNYJN0UJCx+WSXeJx0ijkKzpCl6MjMZNH9TPGAbRpcwzDwtgJptF0ox4c4muxMott5SJVxNfU7lL2MHY7oDSKtM3ceBJzBEQxLR1lAuNj6Xj4lQk46fA7eJQZahFLEvhQRSq31pIauPxnGKCriYdxUakwI9g/wUzokgG50q9OmkepWm3VeFIFC4U08vvaH7BR+lwdBWSW5YQsDMu3OwQ3+0lqZ6BO/2AheUMRbYoXH//vCy1RpOhJ006ApqsBINu5g22Oo0ZzS5hw0TW3P6E2GxseEJANqGDPL96o2HYfxsqc2oPDG70MGKAZTZkH0qdM5h3dSUmTdXss6suRq/Sq9jEi9FYqL3LxgAbjKuptqVbULUURcHx7JJTbEyZ93NVtnLBhzOl2xI3JBFE0EOH4Bl3PhXI6o1zDJz3GK/P3AJmbEibofJkpAji8Qqyc7YRHCIQmGaNWp/Htu3/WMCctw/IavD54tn/EIkLzkUxsPnNW5x5YGf4dbAv27zowLhlovYI6wUGTmGfEATRFHbZvCmFz9FAxZHuBieAfWcfpe4fSjePJHfrAT4D3S926LbtN/WsGSAvngTAFexhL+nxDbP+6wu3NwBuc5LfpqpNe0feeF32XHH9r2zZGCzGFHtTgvMAmJfgRA9ai9q04jpl/KR4LOStP5vPVPEyGrmISIEheOrKS
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: media-tracker-postgres
    type: Opaque
