apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wordpress

resources:
  - namespace.yaml
  - route.yaml
  - sealed-secret.yaml
  - storage.yaml

helmCharts:
  - name: wordpress
    repo: https://charts.bitnami.com/bitnami
    version: 32.1.11
    releaseName: wordpress
    namespace: wordpress
    valuesFile: values.yaml
