# Set to "0" to disable automatic key rotation.
# For simplicity, keep only one backup
keyrenewperiod: "0"

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 32Mi
